### ISSUE TITLE
Adding text-lint

### ISSUE THREAD

**Issue by YutamaKotaro** [react-native-jp/react-native-website#2]

**Comment by YutamaKotaro** [comment]
#12 
という対応をしました！！
現状めっちゃエラーが出るので触ったファイルだけを対象にしたいと思っています！！
めっちゃエラーがでる詳細については #5 
そこで・・・

- textlintにはcachedがあったんですが、ちょっと動かしてみたところみんなで使うのは難しい気がしました(cacheファイルが作られるのと今のエラーは無視できなさそう・・)
- lint-stageでいいかなと思ったんですが、stagedにあげないと引っかからないのでどうしようかと思いました
- 結果、stagedと変更中のファイルを対象にlintをかけられるようにしました！

って感じなんですが・・・・もっといいやり方ありますかね・・・？

**Comment by Naturalclar** [comment]
@YutamaKotaro 
textlintのcached機能を、stagedのファイルに使うだけというのがシンプルで良いかもと思いました！

```
"format": "textlint --cache $(git diff master --name-only) --fix",
```

こんな感じで使えるかなと思ってます

**Comment by YutamaKotaro** [comment]
おおおおお・・・・シンプル・・・。さすがです・・・！！

こちらを採用させていただきます！！
