### ISSUE TITLE
allcontributer入れるのはどうでしょう？

### ISSUE THREAD

**Issue by nitaking** [react-native-jp/react-native-website#7]
こういうOSSリポジトリで [allcontributors](https://allcontributors.org/)をいれるとcontributorのモチベーションにもつながって良いと思うのですが、どうでしょう。

運用方法は、PRにて @allcontributor にコメントを投げると、自動的にREADME更新のPRを allcontributer が自動で作成してくれます。

更新後のREADMEは↓こんな感じです。

![image](https://user-images.githubusercontent.com/10850034/107461981-73fe9100-6b9e-11eb-8c5a-4306551d752c.png)

**Comment by nitaking** [comment]
権限を持っていないのでBot追加Requestしました。
![image](https://user-images.githubusercontent.com/10850034/107462836-503c4a80-6ba0-11eb-8a45-0b23dfe0e64d.png)

**Comment by rena-h** [comment]
@nitaking 
Bot追加されていました！

動作もうまくいきました
https://github.com/react-native-jp/react-native-website/pull/20

**Comment by nitaking** [comment]
@rena-h 

おお！いい感じですね！
（bot入れるだけで他の設定不要なの、ステキ）

導入完了ということでクローズしますね！
